const config = {
  RAZORPAY_API_KEY: "rzp_test_krnysMBlCrvyoP",
  RAZORPAY_API_SECRET: "GiOaCCq8BGxuZ1onrr3gc2s1",
  PAYTM_MID: "AaffLp25230346227162",
  PAYTM_WEBSITE: "WEBSTAGING",
  PAYTM_CHANNEL_ID: "WEB",
  PAYTM_INDUSTRY_TYPE_ID: "Retail",
  PAYTM_MERCHANT_KEY: "FNzu8Vs0uTnLtHe9",
  //   PAYTM_ENVIRONMENT=local
  // PAYTM_MERCHANT_ID=AaffLp25230346227162
  // PAYTM_MERCHANT_KEY=FNzu8Vs0uTnLtHe9
  // PAYTM_MERCHANT_WEBSITE=WEBSTAGING
  // PAYTM_CHANNEL=WEB
  // PAYTM_INDUSTRY_TYPE=Retail
};

module.exports = config;